---
label: Site Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: baseURL
  label: Base URL
  description: Hostname (and path) to the root
  hidden: true
- type: field_group
  name: params
  label: Params
  description: Site parameters
  config:
    required: true
  fields:
  - type: text
    name: domain
    label: Domain
    description: 'The domain of your site, including the protocol, e.g. https://mysite.com/'
  - type: file
    name: favicon
    label: Favicon
    description: A square icon that represents your website
  - type: select
    name: color_scheme
    label: Color Scheme
    description: The color scheme used for the site.
    default: light
    config:
      required: true
      source:
        type: custom
      options:
      - light
      - dark
  - type: select
    name: accent_color
    label: Accent Color
    description: The accent color of the site.
    default: pink
    config:
      required: true
      source:
        type: custom
      options:
      - pink
      - green
      - blue
      - violet
      - yellow
  - type: field_group
    name: header
    label: Header Configuration
    fields:
    - type: include
      name: include_header
      label: Header Configuration
      template: header
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
    - type: include
      name: include_footer
      label: Footer Configuration
      template: footer
pages:
- config.yaml
